openapi: 3.0.3
info:
  title: Enman API
  version: 0.1.1
servers:
- description: Local development server
  url: http://localhost:1234
tags:
- description: Endpoints related to health checks and status monitoring
  name: health
- description: "Endpoints related to authentication (signup, login, etc.)"
  name: auth
paths:
  /up:
    get:
      operationId: up
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthOkResponse"
          description: OK
      summary: Health check
      tags:
      - health
  /auth/signup:
    post:
      operationId: authSignup
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthSignupRequest"
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthSignupResponse"
          description: テナントおよび管理者ユーザーの作成に成功
        default:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Error Response
      summary: 新規テナント作成 + 管理者ユーザー登録
      tags:
      - auth
  /auth/login:
    post:
      operationId: authLogin
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthLoginRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthLoginResponse"
          description: ログイン成功
        default:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
          description: Error Response
      summary: ログイン
      tags:
      - auth
components:
  schemas:
    HealthOkResponse:
      example:
        test: 123
        message: I'm up!
      properties:
        message:
          example: I'm up!
          type: string
        test:
          example: 123
          type: integer
      type: object
    AuthSignupResponse:
      example:
        user:
          name: 太郎
          id: 1
          email: taro@example.com
        tenant:
          name: 田中家
        token: eyJhbGciOiJIUzI1NiJ9...
      properties:
        user:
          $ref: "#/components/schemas/UserData"
        tenant:
          $ref: "#/components/schemas/TenantData"
        token:
          description: JWT アクセストークン
          example: eyJhbGciOiJIUzI1NiJ9...
          type: string
      required:
      - tenant
      - token
      - user
      type: object
    UserData:
      example:
        name: 太郎
        id: 1
        email: taro@example.com
      properties:
        id:
          example: 1
          readOnly: true
          type: integer
        name:
          example: 太郎
          type: string
        email:
          example: taro@example.com
          format: email
          type: string
      required:
      - email
      - id
      - name
      type: object
    TenantData:
      example:
        name: 田中家
      properties:
        name:
          example: 田中家
          type: string
      required:
      - name
      type: object
    ErrorResponse:
      example:
        errors:
          email:
          - has already been taken
      properties:
        errors:
          additionalProperties:
            items:
              type: string
            type: array
          example:
            email:
            - has already been taken
          type: object
      required:
      - errors
      type: object
    AuthSignupRequest:
      example:
        tenant_name: 田中家
        password: Password123
        password_confirmation: Password123
        user_name: 太郎
        email: taro@example.com
      properties:
        tenant_name:
          description: 家族の名前
          example: 田中家
          maxLength: 50
          minLength: 1
          type: string
        user_name:
          description: ユーザーの名前
          example: 太郎
          maxLength: 25
          minLength: 1
          type: string
        email:
          description: ログインメールアドレス
          example: taro@example.com
          format: email
          type: string
        password:
          description: ログインパスワード（8文字以上・英数混合）
          example: Password123
          minLength: 8
          type: string
        password_confirmation:
          description: パスワード（確認用）
          example: Password123
          minLength: 8
          type: string
      required:
      - email
      - password
      - password_confirmation
      - tenant_name
      - user_name
      type: object
    AuthLoginResponse:
      example:
        user:
          name: 太郎
          email: taro@example.com
        token: eyJhbGciOiJIUzI1NiJ9...
      properties:
        user:
          $ref: "#/components/schemas/UserData_1"
        token:
          description: JWT アクセストークン
          example: eyJhbGciOiJIUzI1NiJ9...
          type: string
      required:
      - token
      - user
      type: object
    UserData_1:
      example:
        name: 太郎
        email: taro@example.com
      properties:
        name:
          example: 太郎
          type: string
        email:
          example: taro@example.com
          format: email
          type: string
      required:
      - email
      - name
      type: object
    ErrorResponse_1:
      properties:
        errors:
          additionalProperties:
            items:
              type: string
            type: array
          example:
            base:
            - メールアドレスまたはパスワードが正しくありません
          type: object
      required:
      - errors
      type: object
    AuthLoginRequest:
      example:
        password: Password123
        email: taro@example.com
      properties:
        email:
          description: ログインメールアドレス
          example: taro@example.com
          format: email
          type: string
        password:
          description: ログインパスワード
          example: Password123
          minLength: 8
          type: string
      required:
      - email
      - password
      type: object
